#!/bin/bash
files_commit=$(git diff --cached --name-only)

for file in $files_commit; do
    if [[ -f $file && $file =~ pm$\|pl$ ]]
    then
        if [[ "$(perltidy -nst -b -bext='/bk' $file)" -gt 0 ]]; then
         echo >&2 "There was an error when running perltidy $file; please see the error file for more info"
           exit 1
       fi
       real_files_commit="$read_files_commit $file"
    fi
done

if [[ -n "$real_files_commit" ]]; then
	git add $real_files_commit
fi
